project_id = "mdwdnwgqnditzvwehdsk"

[functions.get-event-participants]
verify_jwt = true

[functions.send-event-confirmation]
verify_jwt = true

[functions.submit-contact]
verify_jwt = false

[functions.register-event]
verify_jwt = true

[functions.send-admin-email]
verify_jwt = true
