// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdwdnwgqnditzvwehdsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kd2Rud2dxbmRpdHp2d2VoZHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDU1MTQsImV4cCI6MjA2NzEyMTUxNH0.1fxMay0kFNNs41D2LRMu8D7IR0vIhUSMu2_brHd0ugE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});